blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/lovecoal0928/ToDo/issues/new?template=custom.md&projects=lovecoal0928%2FToDo%2F1&labels=ToDo
